### PR TITLE
Add a codespell check

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by mathertel** [comment]
Only 2 typos found. Great.
Thanks for the GitHub actions file. I am not familiar with these actions (yet).
Do you know if there is an Arduino build task available to check compilation results or source code static analysis?

**Comment by peternewman** [comment]
> Thanks for the GitHub actions file. I am not familiar with these actions (yet).

Yeah not too much to know with a built action like the codespell one, just some program specific config (like if you were running it on the CLI). Compared to running the tool yourself where the action would have to download and install lots of stuff.

The lack of other typos may be because I'd added a codespell run to Travis and fixed them at that point:
https://github.com/mathertel/DmxSerial2/pull/14/files?diff=unified&w=1

> Do you know if there is an Arduino build task available to check compilation results or source code static analysis?

I think so, you could start by turning on Travis (.org or .com, despite their claims the former still appears to be alive):
https://github.com/mathertel/DmxSerial2/pull/8#issuecomment-345563151

The next easiest thing is probably just to port the existing Travis PlatformIO config to Github:
https://github.com/mathertel/DmxSerial2/blob/854fb219be571a272f266acc96a46b6bed64e7ba/.travis.yml#L14-L23
https://github.com/mathertel/DmxSerial2/blob/854fb219be571a272f266acc96a46b6bed64e7ba/.travis.yml#L35
https://github.com/mathertel/DmxSerial2/blob/854fb219be571a272f266acc96a46b6bed64e7ba/.travis-ci.sh#L28

But I'll see if I can find the Arduino actions, I was talking to some of their people about codespell a while back.

**Comment by peternewman** [comment]
It looks like @per1234 has indeed worked their magic, see for example:
https://github.com/arduino-libraries/Arduino_APDS9960/tree/master/.github/workflows

Which I'll open a new PR to test out...

**Comment by peternewman** [comment]
I think we all got a bit distracted with the other actions in #35 and beyond. Can this be merged as is given it's distinct from them?

**Pull request merged**
